### ISSUE TITLE
MsdnBooksXmlSample fails with HTTP error 403 (forbidden)

### ISSUE THREAD

**Issue by atifaziz** [weblinq/WebLinq#145]
Check-out commit 14ecd1981c54f2c726b151eb5fc09e666731c3e3 (latest at time of reporting) after cloning this repo.

Run the `MsdnBooksXmlSample` sample using the following command-line:

    dotnet run -p eg -f netcoreapp3.1 -- MsdnBooksXmlSample

The samples fails at run-time with the following error:

```
==============================================================================
MsdnBooksXmlSample
------------------------------------------------------------------------------
System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WebLinq.HttpQuery.HttpFetchAsync[T](IHttpClient http, HttpConfig config, HttpMethod method, Uri url, HttpContent content, HttpOptions options, Func`3 responseSelector, Func`5 redirectionSelector) in A:\WebLinq\src\Core\HttpQuery.cs:line 190
   at WebLinq.HttpQuery.SendAsync(IHttpClient http, HttpConfig config, Int32 id, HttpMethod method, Uri url, HttpContent content, HttpOptions options) in A:\WebLinq\src\Core\HttpQuery.cs:line 52
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServices.cs:line 22
   at System.Reactive.Linq.ObservableImpl.GetEnumerator`1.MoveNext() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\GetEnumerator.cs:line 74
   at WebLinq.Samples.Program.Wain(String[] args) in A:\WebLinq\eg\Program.cs:line 75
   at WebLinq.Samples.Program.Main(String[] args) in A:\WebLinq\eg\Program.Main.cs:line 11
```

**Comment by atifaziz** [comment]
Same problem over cURL:

```
❯ curl.exe -vsL https://msdn.microsoft.com/en-us/library/ms762271.aspx
*   Trying 23.205.182.3...
* TCP_NODELAY set
* Connected to msdn.microsoft.com (23.205.182.3) port 443 (#0)
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 183 bytes...
* schannel: sent initial handshake data: sent 183 bytes
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 165
* schannel: encrypted data buffer: offset 165 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 1460
* schannel: encrypted data buffer: offset 1625 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 566
* schannel: encrypted data buffer: offset 2191 length 4096
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /en-us/library/ms762271.aspx HTTP/1.1
> Host: msdn.microsoft.com
> User-Agent: curl/7.55.1
> Accept: */*
> 
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 186
* schannel: encrypted data buffer: offset 186 length 103424
* schannel: decrypted data length: 157
* schannel: decrypted data added: 157
* schannel: decrypted data cached: offset 157 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 157 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 157
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 403 Forbidden
< Content-Type: text/html
< Content-Length: 25
< Date: Fri, 14 Aug 2020 12:39:36 GMT
< Connection: keep-alive
< 
{ [25 bytes data]
* Connection #0 to host msdn.microsoft.com left intact
Unable to process request
```

However, using a simple user agent string like `Mozilla/5.0` just works:

```
❯ curl.exe -vsL -H User-Agent:Mozilla/5.0 https://msdn.microsoft.com/en-us/library/ms762271.aspx
*   Trying 23.205.182.3...
* TCP_NODELAY set
* Connected to msdn.microsoft.com (23.205.182.3) port 443 (#0)
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 183 bytes...
* schannel: sent initial handshake data: sent 183 bytes
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 165
* schannel: encrypted data buffer: offset 165 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 1460
* schannel: encrypted data buffer: offset 1625 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 566
* schannel: encrypted data buffer: offset 2191 length 4096
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with msdn.microsoft.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /en-us/library/ms762271.aspx HTTP/1.1
> Host: msdn.microsoft.com
> Accept: */*
> User-Agent:Mozilla/5.0
> 
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 490
* schannel: encrypted data buffer: offset 490 length 103424
* schannel: decrypted data length: 461
* schannel: decrypted data added: 461
* schannel: decrypted data cached: offset 461 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 461 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 461
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 301 Moved Permanently
< Cache-Control: public,max-age=600
< Location: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms762271(v=vs.85)?redirectedfrom=MSDN
< Request-Context: appId=cid-v1:f9d2ef03-1ca1-4aa6-8028-17b214f45eeb
< Strict-Transport-Security: max-age=2592000
< X-RedirectDb-Info: Content level redirect, Id: ms762271, Locale: en-us, Pfv: vs.85
< Content-Length: 0
< Date: Fri, 14 Aug 2020 12:42:41 GMT
< Connection: keep-alive
< 
* Connection #0 to host msdn.microsoft.com left intact
* Issue another request to this URL: 'https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ms762271(v=vs.85)?redirectedfrom=MSDN'
*   Trying 23.50.102.187...
* TCP_NODELAY set
* Connected to docs.microsoft.com (23.50.102.187) port 443 (#1)
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 1/3)
* schannel: checking server certificate revocation
* schannel: sending initial handshake data: sending 183 bytes...
* schannel: sent initial handshake data: sent 183 bytes
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 2/3)
* schannel: failed to receive handshake, need more data
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 4096
* schannel: encrypted data buffer: offset 4096 length 4096
* schannel: encrypted data length: 118
* schannel: encrypted data buffer: offset 118 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 1460
* schannel: encrypted data buffer: offset 1578 length 4096
* schannel: received incomplete message, need more data
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 613
* schannel: encrypted data buffer: offset 2191 length 4096
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 2/3)
* schannel: encrypted data got 258
* schannel: encrypted data buffer: offset 258 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with docs.microsoft.com port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /en-us/previous-versions/windows/desktop/ms762271(v=vs.85)?redirectedfrom=MSDN HTTP/1.1
> Host: docs.microsoft.com
> Accept: */*
> User-Agent:Mozilla/5.0
> 
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 1460
* schannel: encrypted data buffer: offset 1460 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 1460 length 103424
* schannel: encrypted data got 10220
* schannel: encrypted data buffer: offset 11680 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 102400 bytes
* schannel: encrypted data buffer: offset 11680 length 103424
* schannel: encrypted data got 11680
* schannel: encrypted data buffer: offset 23360 length 103424
* schannel: decrypted data length: 16384
* schannel: decrypted data added: 16384
* schannel: decrypted data cached: offset 16384 length 102400
* schannel: encrypted data length: 6947
* schannel: encrypted data cached: offset 6947 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 16384
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Content-Type: text/html
< ETag: "eIVcL7FXjcslbhvjZYCukRs+Ne4gz8HEHouZ/7OanWg="
< Request-Context: appId=cid-v1:21aee9e4-1cf5-4750-b2bd-78b2747f4211
< X-Datacenter: wus
< X-Frame-Options: SAMEORIGIN
< x-content-type-options: nosniff
< X-UA-Compatible: IE=edge
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< X-Rendering-Stack: Dynamic
< Cache-Control: public, max-age=127
< Expires: Fri, 14 Aug 2020 12:44:48 GMT
< Date: Fri, 14 Aug 2020 12:42:41 GMT
< Content-Length: 33721
< Connection: keep-alive
< Akamai-Cache-Status: Hit from child
< report-to: {"group":"network-errors","max_age":604800,"endpoints":[{"url":"https://mdec.nelreports.net/api/report?cat=mdocs"}]}
< nel: {"report_to":"network-errors","max_age":604800,"success_fraction":0.01,"failure_fraction":1.0}
< 
* schannel: client wants to read 18171 bytes
* schannel: encrypted data buffer: offset 6947 length 103424
* schannel: encrypted data got 1460
* schannel: encrypted data buffer: offset 8407 length 103424
* schannel: failed to decrypt data, need more data
* schannel: schannel_recv cleanup
* schannel: client wants to read 18171 bytes
* schannel: encrypted data buffer: offset 8407 length 103424
* schannel: encrypted data got 9822
* schannel: encrypted data buffer: offset 18229 length 103424
* schannel: decrypted data length: 9026
* schannel: decrypted data added: 9026
* schannel: decrypted data cached: offset 9026 length 102400
* schannel: encrypted data length: 9174
* schannel: encrypted data cached: offset 9174 length 103424
* schannel: decrypted data length: 9145
* schannel: decrypted data added: 9145
* schannel: decrypted data cached: offset 18171 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 18171 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 18171
* schannel: decrypted data buffer: offset 0 length 102400
* Connection #1 to host docs.microsoft.com left intact
```
