### ISSUE TITLE
AutoRedirection sample fails with a 404

### ISSUE THREAD

**Issue by atifaziz** [weblinq/WebLinq#146]
Check-out commit 14ecd1981c54f2c726b151eb5fc09e666731c3e3 (latest at time of reporting) after cloning this repo.

Run the `AutoRedirection` sample using the following command-line:

    dotnet run -p eg -f netcoreapp3.1 -- AutoRedirection

The samples fails with the following run-time error:

```
==============================================================================
AutoRedirection
------------------------------------------------------------------------------
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at WebLinq.HttpQuery.HttpFetchAsync[T](IHttpClient http, HttpConfig config, HttpMethod method, Uri url, HttpContent content, HttpOptions options, Func`3 responseSelector, Func`5 redirectionSelector) in A:\WebLinq\src\Core\HttpQuery.cs:line 190
   at WebLinq.HttpQuery.SendAsync(IHttpClient http, HttpConfig config, Int32 id, HttpMethod method, Uri url, HttpContent content, HttpOptions options) in A:\WebLinq\src\Core\HttpQuery.cs:line 52
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServicesImpl.cs:line 16
   at System.Reactive.ExceptionHelpers.ThrowIfNotNull(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\ExceptionServices.cs:line 22
   at System.Reactive.Linq.ObservableImpl.GetEnumerator`1.MoveNext() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\GetEnumerator.cs:line 74
   at WebLinq.Samples.Program.Wain(String[] args) in A:\WebLinq\eg\Program.cs:line 75
   at WebLinq.Samples.Program.Main(String[] args) in A:\WebLinq\eg\Program.Main.cs:line 11
```

Also reproducible with cURL:

```
❯ curl -vsL http://httpbin.org/redirect-to?url=http://example.com/
*   Trying 54.236.246.173...
* TCP_NODELAY set
* Connected to httpbin.org (54.236.246.173) port 80 (#0)
> GET /redirect-to?url=http://example.com/ HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: awselb/2.0
< Date: Fri, 14 Aug 2020 12:51:25 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host httpbin.org left intact
```

**Comment by atifaziz** [comment]
This seems to be due to postmanlabs/httpbin#617.
